name: Residence
main: net.t00thpick1.residence.Residence
version: 3.0.0-ALPHA-SNAPSHOT
description: Cuboid Residence Plugin
author: t00thpick1
authors: [t00thpick1,bekvon]
contributors: [nate302,lemon42,smbarbour,inorixu,Shayana_fr]
softdepend: [Vault,WorldEdit]
commands:
  residence:
    description: Manage Residences
    usage: §c/res ? for more info
    aliases: [res]
  resadmin:
    description: Residence admin functions.
    usage: §c/res ? or /resadmin ? for more info
  resreload:
    description: Reload the entire residence plugin.
    usage: §c/resreload
  resload:
    description: Load the save file again after you have made modifications.
    usage: §c/resload
permissions:
  residence.admin:
    description: Gives you access to /resadmin
    default: op
    children:
      residence.admin.tp: true
      residence.admin.move: true
      residence.commands: true
  residence.admin.tp:
    description: Allows to override tp flag
    default: op
  residence.admin.move:
    description: Allows to override move flag
    default: op
  residence.commands:
    description: Allows all commands
    default: op
    children:
      residence.commands.create: true
      residence.commands.select: true
  residence.commands.create:
    description: Allows you to create residences
    default: op
  residence.commands.select:
    description: Allows you to select an area to make residences
    default: op
